### ISSUE TITLE
Add a website for displaying conferences

### ISSUE THREAD

**Issue by nikhita** [nikhita/tech-conferences-india#117]
This has been discussed in #60 before but I want to start a fresh issue since this is a bit nuanced and needs a design first.

@tanvibhakta pointed to https://androidstudygroup.github.io/conferences/ in https://twitter.com/padawanjack/status/1065874671600656384 and I like the idea of showing which conferences have CFPs currently open. To incorporate this, we need some changes in how we structure the conferences right now.

If you have ideas about what details should be shown in the website, add a comment to this issue. Please _don't_ create a PR right now.

I'll work on an initial design and post it here. If I end up creating a PR for it, I'll only merge it by [lazy consensus](https://rave.apache.org/docs/governance/lazyConsensus.html) so that the community has a say in it. :)

**Comment by arush-sal** [comment]
Add column headers with start and end date 😬

**Comment by darshancc23** [comment]
A countdown would be cool

**Comment by nikhita** [comment]
I don't have time to work on this and/or review this. I'm going to close this issue for now and will reopen when I have time.

In case you are interested in this, please feel free to fork and create a website on the basis of this repo (with appropriate attribution).
