### ISSUE TITLE
Add DS Conf 2019 to the list

### ISSUE THREAD

**Issue by ashish91** [nikhita/tech-conferences-india#122]
| [DSConf](https://dsconf.in/) | 16 Feb | Pune | Conference on Distributed Systems | No |

Let me know if you need me to create a PR for it. I don't have access rights so couldn't push my branch with changes.

**Comment by nikhita** [comment]
@ashish1729 Thanks for the suggestion! Only owners have rights to push directly to master, so a PR is always ideal.

Having said this, it doesn't look like DSConf supports CFPs? This repo only accepts conferences which have CFPs so if you could point me to a page where it says that CFPs were used while deciding the speakers, I'm happy to accept a PR about this.

**Comment by nikhita** [comment]
@aravindputrevu Awesome! :)

If someone can send a PR, I'm happy to merge it.

**Comment by ashish91** [comment]
@nikhita Here you go https://github.com/nikhita/tech-conferences-india/pull/123.
