### ISSUE TITLE
Remove conferences that don't support CoCs

### ISSUE THREAD

**Issue by Anniepoo** [nikhita/tech-conferences-india#125]
It would be useful to have a column showing whether the conference has a code of conduct displayed on the front page.

It probably makes more sense to just add it to 2019 conferences.

**Comment by nikhita** [comment]
Oh good point! Honestly, I'd like to take it one step further and not accept conferences that don't have CoCs.

If someone could go through the existing 2019 conferences and audit that all of them have CoCs, that'd be great. :)

**Comment by nikhita** [comment]
@Anniepoo thanks again for this! :heart: 

I have edited the title to remove confs that don't support CoCs.

In addition, if someone could send a PR to add to the README that only conferences with CoCs are supported, that'd be super helpful! If noone gets to it by next, I'll do it myself.

Adding the `help wanted` and `good first issue`s on this. :sparkles:

**Comment by Anniepoo** [comment]
in the us I was "no coc, no cfp", but I think there's some room for education in India.

**Comment by Kaushl2208** [comment]
Just have to remove the conferences who don't have their specific COC from the list of 2019? If it is then I am up for it. @nikhita

**Comment by nikhita** [comment]
Fixed by #127 (thanks @Kaushl2208!)
