### ISSUE TITLE
[Feat] Display conferences in sorted order and disable conferences which are already done.

### ISSUE THREAD

**Issue by nimish-gupta** [nikhita/tech-conferences-india#131]

**Comment by nimish-gupta** [comment]
I can create a PR for this one, in PR we can also check that whether when a  new conference is added, it is sorted or not :)

**Comment by nimish-gupta** [comment]
I can create a PR for this one, in PR we can also check that whether when a  new conference is added, it is sorted or not :)

**Comment by nikhita** [comment]
What do you mean by sorted order?

> disable conferences which are already done. 

I understand the intent but it's a lot of maintainer overhead. The README isn't too long now :) so I don't think this is really needed.

**Comment by nimish-gupta** [comment]
So maintainer doesn't need to maintain this, whenever any new pull request will be done and if there is change in the readme file, then we can just right a script that all the conferences are sorted year wise.

> What do you mean by sorted order?
Sorted on the base of month wise. like all conferences listed from Jan - Dec. 

> disable conferences which are already done.
For this we can just create a small server which will look into the readme and check the date of conference, and if it past the date, then it will create a PR for disabling it.

**Comment by nikhita** [comment]
> Sorted on the base of month wise. like all conferences listed from Jan - Dec.

The reverse chronological order is intentional because that lets you know the conferences that would be happening in the near future first.

> For this we can just create a small server which will look into the readme and check the date of conference, and if it past the date, then it will create a PR for disabling it.

I think it adds too much complexity and is not really needed. The list isn't that long and it's sometimes helpful to just see what conferences took place in a year.

**Comment by nimish-gupta** [comment]
> The reverse chronological order
Not reverse.

But yeah there are not much conferences, so we can keep it as it is. Thanks for consideration though.

**Comment by nikhita** [comment]
Sorry for not plus-one-ing this :) but I appreciate the thought and you filing a feature request for this! :100: :medal_sports:
