### ISSUE TITLE
Add MEC.conf

### ISSUE THREAD

**Issue by de-sh** [nikhita/tech-conferences-india#145]
MEC.conf (https://conf.mec.dev) is a conference hosted by Model Engineering College, Kochi and has a CFP open at https://conf.mec.dev/speak. We are a developer community, MEC.dev, behind this 😄

We offer travel assistance to select speakers and accept both hardware and software developers. Also, though this is our first iteration, we intend to have a conference next year too.

**Comment by nikhita** [comment]
@de-sh Thanks for opening the issue!

https://github.com/nikhita/tech-conferences-india/pull/141 adds it to the README (thanks again @kurianbenoy!) :tada:

**Comment by de-sh** [comment]
Thanks @nikhita
