### ISSUE TITLE
GopherCon India listed under wrong year.

### ISSUE THREAD

**Issue by arush-sal** [nikhita/tech-conferences-india#15]
The GopherCon India is listed under the year 2016, Feb, but it rather should have been under the year 2017, Feb.

**Comment by nikhita** [comment]
@arush-sal Hi, not sure I follow. The list has conferences for _both_ the year 2016 and 2017. GopherCon India is listed both in 2016 and 2017.

**Comment by arush-sal** [comment]
Yup you are right, my bad :(

**Comment by nikhita** [comment]
@arush-sal No problem! Thanks for reporting though. Appreciate it! :)
