### ISSUE TITLE
Summits?

### ISSUE THREAD

**Issue by championshuttler** [nikhita/tech-conferences-india#16]
can we add summits too?

**Comment by amitkumarj441** [comment]
Yes @championshuttler ! 

You can add tech {conferences + summits} and can't wait to see your PR.

**Comment by nikhita** [comment]
@championshuttler Yes, that sounds good. Please go ahead! 

You don't necessarily need to submit a PR. If you'd like, you can also mention the summits in this issue and I'll add it myself. :)
