### ISSUE TITLE
PyConf Hyd 2020

### ISSUE THREAD

**Issue by snehithallamraju** [nikhita/tech-conferences-india#186]
Can you kindly add the details for Pyconf Hyderabad 2020 to the page? Details are as below

Name and link : PyConf Hyderabad 2020 (https://pyconf.hydpy.org/2020/)
Date : 5th - 6th December 2020
Venue : Virtual
Description : PyConf Hyderabad is the regional gathering for the community that uses and develops the open-source Python Programming Language. And this year, it is Virtual!
Scholarship Provided : No

**Comment by inovizz** [comment]
Raised PR #187 for the same.

**Comment by nikhita** [comment]
Done in #187! Thanks for creating the PR real quick, @inovizz! :raised_hands: :tada:
