### ISSUE TITLE
Add more confs

### ISSUE THREAD

**Issue by nikhita** [nikhita/tech-conferences-india#24]
Some more conferences:

- http://www.developermarch.com/developersummit/index.html
- http://www.analyticsindiasummit.com/about/
- https://functionalconf.com/
- http://opensourceindia.in/osidays/
- http://xpconference.in/2017XpConf/

If anyone wants to submit a PR for this, please go ahead! I'll be happy to review and merge it! :tada:

**Comment by sushant-j** [comment]
Would surely love to pitch in! I'll submit a PR later today :)

**Comment by nikhita** [comment]
@sushant-j Yayyyy! Thank you! :)

**Comment by sushant-j** [comment]
Submitted a PR :+1:

**Comment by sushant-j** [comment]
Something I noticed, the 2018 conferences are added in reverse chronological order. Is it intentional? 
I didn't correct it in case it is.

**Comment by nikhita** [comment]
@sushant-j thanks for noticing. It wasn't intentional. I commented on your PR about this. If it's fine with you, can you please fix it in the PR? Or else I'll fix it as a follow up. :smile:

**Comment by nikhita** [comment]
Fixed in #25. Thanks, @sushant-j!
