### ISSUE TITLE
Make the list yearwise

### ISSUE THREAD

**Issue by shivakrishna9** [nikhita/tech-conferences-india#28]
The page is getting longer day to day.
How about listing the conferences by year
For ex: We mention the year in the readme and a link which redirects to the conferences of that year.

**Comment by nikhita** [comment]
@shivakrishna9 Thanks for the suggestion! Yes, I had plans to keep only the current year on the README and move everything else to a separate directory.

Example:
- 2017 conferences stay on the README as-is.
- two more directories are created for `2016` and `2018` and the conferences are moved to a markdown file in those directories (respectively).

Would you like to work on this?

**Comment by shivakrishna9** [comment]
Yes. Sure. I will work on this. :) @nikhita

**Comment by nikhita** [comment]
@shivakrishna9 do you want to continue to work on this?

**Comment by shivakrishna9** [comment]
Yup! Unable to do it as I am away from GitHub since a month.

**Comment by nikhita** [comment]
> Yup! Unable to do it as I am away from GitHub since a month.

No problem, feel free to send a PR when ready. :)

**Comment by techsethi** [comment]
> What next is you need help with ?

**Comment by nikhita** [comment]
@techsethi If you'd like to contribute, see my comment here: https://github.com/nikhita/tech-conferences-india/issues/28#issuecomment-320519797. The plan is to move the conferences according to the year.

Let me know if you have any further questions!

**Comment by techsethi** [comment]
@nikhita Done, please check & merge. Let me know, if there are any issues.

https://github.com/nikhita/tech-conferences-india/pull/39
