### ISSUE TITLE
Add scholarship/price details

### ISSUE THREAD

**Issue by jsroyal** [nikhita/tech-conferences-india#46]
Like most of the conference is paid and very less are free.
It just one thought of mine if you could also add one more column for a range of pricing.
 Second: Also the order should be calendar date-wise.

Because after all see if the tickets price is very high then most of them cancel the plan.
So the idea is here if some can get a fair idea about price before it would save time to know about it and then cancel the plan due to pricing.

**Comment by nikhita** [comment]
That's a cool idea! :+1: Additionally, it would be good to mention conferences which offer scholarships too.

**Comment by jsroyal** [comment]
Oh' I do not aware of it.
> offer scholarships too.

Can you please describe more about?

**Comment by nikhita** [comment]
> Can you please describe more about?

Sure. Some conferences offer scholarships to help fund people to attend. [GopherCon India](http://www.gophercon.in/scholarship/), [RubyConf India](http://rubyconfindia.org/scholarship/) and [GHC](https://ghcindia.anitab.org/ghci-17-student-scholarships/) are a few examples.

**Comment by Sudip7** [comment]
Adding pricing coloum would b really helpful. For example, last year I missed the great Indian developer conference though price was reasonable. But this year, even the early bird tickets cost ₹7500/ day. Not able to decide should I go for it or not. 

Anyway thanks @nikhita for this repo. I was really looking for such thing.

**Comment by nikhita** [comment]
Sorry, I seemed to have missed this:

> Second: Also the order should be calendar date-wise.

It's easier to search and see the latest conferences if it's reverse chronological. It's November now. If I start from Jan, you'll have to scroll all the way to the bottom to see the current events.

**Comment by aravindputrevu** [comment]
@Sudip7 GIDS is a nice conference to attend. Totally worth.

**Comment by nikhita** [comment]
We now have a column for scholarships for the 2019 conferences. :tada: 

Closing this issue. Please reopen if needed.
