### ISSUE TITLE
RUBYCONF INDIA 2018

### ISSUE THREAD

**Issue by rahulkrishnanfs** [nikhita/tech-conferences-india#47]
In 2018 RubyConf India is going to be at Namma Bengaluru
The Chancery Pavilion Hotel, Bengaluru. 9-10 February 2018

http://rubyconfindia.org/

**Comment by championshuttler** [comment]
working on it :)

**Comment by nikhita** [comment]
Fixed in #49. Thanks for sending a PR, @championshuttler!

@rahulkrishnanfs Thanks for creating an issue about adding these conferences. :)
