### ISSUE TITLE
Serve a webpage along with README

### ISSUE THREAD

**Issue by kspviswa** [nikhita/tech-conferences-india#60]
Hey Nikitha,

Thought to have a static live webpage, than a `READ.ME` file. So, I just forked your repo and enabled github-pages on my repo, selected timeline theme and tweaked your `READ.ME` to include past year details automatically in the main `index.html`, which will get rendered automatically from `master` branch.

You can view the generated **live** page here : https://kspviswa.github.io/tech-conferences-india/ .

Have a look & let me know if you want a PR from me.

**Comment by arush-sal** [comment]
@kspviswa The webpage does look pretty nice :heart_eyes: :+1:

**Comment by nikhita** [comment]
Thanks for this, @kspviswa! I am travelling right now so I just wanted to let you know that it might be a few days until I can get a deeper look at this. But it looks good on a high level! 👍

**Comment by nikhita** [comment]
@kspviswa I have had the idea of creating the website in the back of my mind but didn't have the time to do so. I like your website as well, but I'd like two main things/changes here:

- the website should not be an exact mirror of the README. The idea is that the website should provide some more benefits over the README.
- another theme, maybe? But that's just me. :)

I have some ideas about the website and I'll probably get it in a couple of weeks. Will ping you for a review surely. 👍

**Comment by kspviswa** [comment]
@nikhita , the main intent here for me is "automation". Serving a static webpage out of READ.ME automatically is the key. Since the main mode of contribution to this repo is via read.me file , as & when new conference details gets merged to READ.ME file, new content will get automatically served by Github. That's the key. Putting up a website with more details etc would be a different ball game altogether.

Finally, if you are not gonna need this PR as of now, then let me know if I can go-ahead and publishing this webpage as part of my blog. 

Cheers!

**Comment by nikhita** [comment]
> Finally, if you are not gonna need this PR as of now, then let me know if I can go-ahead and publishing this webpage as part of my blog.

Sorry for replying so late!

I would like to get to a webpage at _some_ point but I don't have the bandwidth for it right now. I am fine with the README for now.

I would like to have a proper website for _this_ repo; but I am not opposed to you publishing it on your website. However, please provide proper attribution back to this repo on your website.

I see that it references https://github.com/kspviswa/tech-conferences-india, which is ok, but if you are basing off a website off the list of conferences from this repo, it's only fair if you provide proper attribution as well.

**Comment by kspviswa** [comment]
Hey @nikhita,

I don't intend to plagiarize your work. I just did that to demonstrate automatic webpage generation from READ.ME . That's the reason, I have never referred this or published a blog post etc. I'll take it down if you feel so. Let me know.

**Comment by kspviswa** [comment]
@nikhita ,

I took it down.

**Comment by nikhita** [comment]
@kspviswa I don't mind if you keep it, just referencing it back here would be ok :)

Sorry if I came off rudely, text is not the best way of conveying/communication. :)
