### ISSUE TITLE
Add Oracle Code conference

### ISSUE THREAD

**Issue by sandeepyohans** [nikhita/tech-conferences-india#75]
# ORACLE CODE - Bengaluru - April 10, 2018

Online Registration for this event is now closed. Registration will be open on the day of the event at the venue subject to seat availability.

**Venue**
ITC Gardenia No 1, Residency Road Bengaluru, Karnataka- 560025 India
[Google Map](https://www.google.com/maps/place/ITC+Gardenia/@12.9669042,77.5935633,17z/data=!3m1!4b1!4m7!3m6!1s0x3a0276dd2cf216d3:0x523e0c08edd084f2!5m1!1s2018-03-31!8m2!3d12.966899!4d77.595752)

**Comment by aravindputrevu** [comment]
@sandeepyohans Please raise a PR for the same. 
Oracle does code some more places in India. Here is the link with more details : https://developer.oracle.com/code

**Comment by sandeepyohans** [comment]
Hi @aravindputrevu I realised that todays Oracle Code conf is missed out in the list. I opened this issue after reading the comment in the Contribution section, which says,
> If you don't have time to send in a Pull Request, no worries, just open an issue and I'll look into it.
I do get regular updates from Oracle, I was at Oracle Code Hyderabad. Hope this helps in keeping the list updated.

**Comment by aravindputrevu** [comment]
Yes. Interesting. I spoke at Oracle Code Hyderbad.

**Comment by nikhita** [comment]
@sandeepyohans Thanks for creating the issue. I'll create a PR by the end of this week if noone gets to it sooner.

**Comment by sandeepyohans** [comment]
@aravindputrevu Wow! I am glad to know that you spoke at OracleCode! There were many sessions happening in parallel. Is there a way to get the recording of event videos? Would like to hear you. 
@nikhita I am glad to get connected here!

**Comment by aravindputrevu** [comment]
@sandeepyohans https://www.youtube.com/channel/UCdDhYMT2USoLdh4SZIsu_1g/videos
or you can get references here : https://bit.ly/OracleCode

**Comment by sandeepyohans** [comment]
@aravindputrevu thank you for sharing links. Will go through it.
