### ISSUE TITLE
Support workshops

### ISSUE THREAD

**Issue by swapagarwal** [nikhita/tech-conferences-india#81]
I, for one, would be very interested if we include a list of upcoming tech workshops in India.
@nikhita Would you be willing to support this? 😇

**Comment by nikhita** [comment]
> @nikhita Would you be willing to support this?

I'm not particularly opposed to this but can you give me a few examples of what you have in mind?

**Comment by thayumaanavan** [comment]
If it’s college workshops, then list might get huge. If it’s general one, then it should be fine.

**Comment by nikhita** [comment]
> If it’s college workshops, then list might get huge. If it’s general one, then it should be fine.

Yeah, I'm afraid of scope creep here.

**Comment by nikhita** [comment]
>  The scope I had in mind was to collect upcoming workshops (not college ones), say from rootconf, jsfoo, etc.

I might be mistaken here :) but aren't these workshops held as part of the conference?

**Comment by swapagarwal** [comment]
Yes, but sometimes I'm only interested in a particular workshop and not the whole conference..
Right now, I open each conference and check out the workshops offered there (not sure how many others do the same though) :)

**Comment by swapagarwal** [comment]
> If we start listing workshops, it will be hard to justify which ones get a seat and which ones don't.

Makes sense.
> I would like to limit this repo only for conferences for now. Sorry!

No problem! 😅
