### ISSUE TITLE
Himalaya Crypto Summit

### ISSUE THREAD

**Issue by abbasip** [nikhita/tech-conferences-india#84]
| [Himalaya Crypto Summit 2018]( http://capitalexchange.tech) | 25th & 26th May | Taj Apollo Bunder Mumbai | Blockchain Summit

**Comment by abbasip** [comment]
Book Your Tickets Here <ahref=http://capitalexchange.tech/tickets.php><\a>

**Comment by nikhita** [comment]
2018 is almost over, so I'll close this. Thanks for creating the issue though!
