### ISSUE TITLE
CYPHER Analytics India Summit 2018

### ISSUE THREAD

**Issue by tnmurthy** [nikhita/tech-conferences-india#90]
| CYPHER Analytics India Summit 2018 | 26th to 28th September | Hotel Radisson Blu Bangalore India | Analytics Summit

**Comment by aravindputrevu** [comment]
is there a CFP link to submit proposal to CYPHER? @tnmurthy

**Comment by nikhita** [comment]
> I'm not sure, you can submit a query with them at this link

@tnmurthy thanks for creating an issue for this.

However, I want to avoid adding commercial conferences or confs without CFPs. From a glance through their website, it doesn't look like they accept CFPs. I am going to close this issue for now.

If someone can come up with a confirmation that they support CFPs, I am happy to reopen and add it to the list.
