### ISSUE TITLE
2019 Conf's

### ISSUE THREAD

**Issue by DevS1993** [nikhita/tech-conferences-india#94]
Can we start including 2019 conf's ?

example : Ruby Conf India [Jan 2019](https://www.rubyconfindia.org/)

**Comment by nikhita** [comment]
> Can we start including 2019 conf's ?

Sorry, saw this issue now. Have commented on the PR: https://github.com/nikhita/tech-conferences-india/pull/95#discussion_r209448014 about it.

**Comment by nikhita** [comment]
I'll close this since the comment answers it.
